sudo: required
services:
  - docker

before_install:
  - docker build -t geoteo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true geoteo/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-444158920745"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECURE_KEY"
